### ISSUE TITLE
Main vs. Test Robot

### ISSUE THREAD

**Issue by jacksondm33** [RoboEagles4828/TestRobot#1]
Maybe we can make the test robot repository a fork of the main robot repository because of their similarities. It is annoying copying code from one to the other. 
Also, just because we use python doesn't mean the repository name has to have "Py" in it. We should rename "MecanumPy" and "TractionPy" to fit what they actually are.

**Comment by CheezBallzPi** [comment]
Test robot should probably still be separate, as we may or may not keep this chassis even after this year. Also agreed with a name change.
